name: quarmen
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - qiskit
  - qiskit-ibm-runtime
  - pennylane
  - pip
  - pip:
     - qiskit-algorithms
     - qiskit-aer
     - notebook
     - pylatexenc
     - matplotlib
     - ipywidgets
     - seaborn